# Generated by Django 4.2.11 on 2025-02-03 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usertouser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertouser',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
