# Generated by Django 4.2.11 on 2025-01-30 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('carts', '0002_alter_carts_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='carts',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carts', to='users.profile'),
        ),
    ]
