# Generated by Django 4.2.4 on 2024-02-19 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_animalstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='animal_image',
            field=models.ImageField(default='default_animal.jpg', upload_to='animal_pics'),
        ),
    ]
