# Generated by Django 4.2.4 on 2024-01-25 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='animalstatus',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
