# Generated by Django 4.2.11 on 2025-01-20 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_alter_categories_options_alter_categories_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.categories'),
        ),
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(default='default_animal.jpg', upload_to='catalog_pics'),
        ),
    ]
