# Generated by Django 4.2.11 on 2025-01-30 13:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carts', '0003_carts_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('goods', '0004_alter_products_category_alter_products_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Phone number')),
                ('requires_delivery', models.BooleanField(default=False, verbose_name='Delivery required')),
                ('delivery_address', models.TextField(blank=True, null=True, verbose_name='Delivery adress')),
                ('payment_on_get', models.BooleanField(default=False, verbose_name='On delivery paymant')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Paid')),
                ('status', models.CharField(default='In progress', max_length=50, verbose_name='Order status')),
                ('cart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='carts.carts', verbose_name='Busket')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'db_table': 'order',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Product name')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Price')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Quantity')),
                ('created_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Sold date')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order', verbose_name='Order')),
                ('product', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='goods.products', verbose_name='Product')),
            ],
            options={
                'db_table': 'order_item',
                'ordering': ('id',),
            },
        ),
    ]
